print("What do you call a fat cat")
print()
print()
print()
print("a fat cat")
print()
name = input("what is your name? ")
print(f"hello {name}")
name = input("what is your favorite color?")
print(f"thats cool i also like {name} but my favorite is blue")
print()
print()
name = input("how has your day been?")
print(f"oh {name} me too")